### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by ajmalmohammedn** [riquedev/django-login-history2#14]
Traceback (most recent call last):
  File "manage.py", line 31, in <module>
    main()
  ...
ModuleNotFoundError: No module named 'django_login_history2'

Environment:

Django version: [e.g., 4.2.7]
Python version: [e.g., 3.8.5]
Operating System: [e.g., macOS]

**Comment by riquedev** [comment]
Hello!
I checked here and the package actually has pip problems, I'll adjust it.

**Comment by riquedev** [comment]
pip was out of date with respect to the repository, so I forced version 0.0.3.

I ask that you use the

```console
pip install django-login-history2 --upgrade
```
To force the use of 0.0.3, if the problem persists, I ask you to reopen this issue.
