### ISSUE TITLE
It could be useful to have the IP address even it's not routable

### ISSUE THREAD

**Issue by pjuhen** [riquedev/django-login-history2#17]
Hi,

as programmed, the IP address, when it's not routable is always 8.8.8.8.

It could be useful to have the IP address for application running on a private network.

Thanks,

**Comment by pjuhen** [comment]
Hereafter  is a proposed modification, that works for me :

@receiver(user_logged_in)
def post_login(sender, user, request, **kwargs):
    client_ip, is_routable = get_client_ip(request)
    method_path = GEOLOCATION_METHOD
    result = None

    if  not client_ip:
        client_ip = GEOLOCATION_PLACEHOLDER_IP
    else:
        if not is_routable:
            result = { "error": True, "reason": "Address not routable"}

        elif method_path:
            module_name, func_name = method_path.rsplit('.', 1)
            try:
                module = importlib.import_module(module_name)
                geolocation_func = getattr(module, func_name)
                result = geolocation_func(client_ip)
            except (ImportError, AttributeError) as er:
                raise ValueError("Invalid geolocation method specified in settings.\n", er) from er

        if not result:
            result = get_geolocation_data(client_ip)

        assert isinstance(result, dict)

        mapped_fields = {}

        for key, value in result.items():

            if key in GEOLOCATION_BLOCK_FIELDS:
                continue

            try:
                _ = Login._meta.get_field(key)
                mapped_fields[key] = value
            except FieldDoesNotExist:
                pass

        _ = Login.objects.create(
            user=user,
            ip=client_ip,
            user_agent=request.META.get('HTTP_USER_AGENT', ''),
            ip_info=result,
            **mapped_fields
        )

**Comment by riquedev** [comment]
> Hereafter is a proposed modification, that works for me :
> 
> @receiver(user_logged_in) def post_login(sender, user, request, **kwargs): client_ip, is_routable = get_client_ip(request) method_path = GEOLOCATION_METHOD result = None
> 
> ```
> if  not client_ip:
>     client_ip = GEOLOCATION_PLACEHOLDER_IP
> else:
>     if not is_routable:
>         result = { "error": True, "reason": "Address not routable"}
> 
>     elif method_path:
>         module_name, func_name = method_path.rsplit('.', 1)
>         try:
>             module = importlib.import_module(module_name)
>             geolocation_func = getattr(module, func_name)
>             result = geolocation_func(client_ip)
>         except (ImportError, AttributeError) as er:
>             raise ValueError("Invalid geolocation method specified in settings.\n", er) from er
> 
>     if not result:
>         result = get_geolocation_data(client_ip)
> 
>     assert isinstance(result, dict)
> 
>     mapped_fields = {}
> 
>     for key, value in result.items():
> 
>         if key in GEOLOCATION_BLOCK_FIELDS:
>             continue
> 
>         try:
>             _ = Login._meta.get_field(key)
>             mapped_fields[key] = value
>         except FieldDoesNotExist:
>             pass
> 
>     _ = Login.objects.create(
>         user=user,
>         ip=client_ip,
>         user_agent=request.META.get('HTTP_USER_AGENT', ''),
>         ip_info=result,
>         **mapped_fields
>     )
> ```

Hello @pjuhen, thanks for the suggestion, if you want, feel free to make PR's that you deem necessary.
Tomorrow I will do this implementation that you mentioned, thanks again!
