### ISSUE TITLE
Not working. Data not stored in database

### ISSUE THREAD

**Issue by fajrulfx** [riquedev/django-login-history2#19]
No error. But the data is not stored in the database at all
![Screenshot 2024-06-15 105753](https://github.com/riquedev/django-login-history2/assets/21325927/3a6109b1-2958-4fb0-856d-88d5ff17fa38)
.

**Comment by DmytroLitvinov** [comment]
I suppose it does not work because of that line of code - https://github.com/riquedev/django-login-history2/blob/b393d928857e611cc7bf66d7cb7792d881c61ddb/django_login_history2/models.py#L69 because of wrong indentation.

It should be that after getting result we create in the end `Login` instance.
